#!/usr/bin/env python3
"""settings-effective: the merged Claude Code settings, with the file that decided each key.

Claude Code reads up to six settings sources and merges them silently: managed policy,
--settings, .claude/settings.local.json, .claude/settings.json, ~/.claude/settings.json,
and a handful of keys from ~/.claude.json. Nothing prints the result. This does, and
names the reasons a key you set is not the one in effect.

    python effective.py                       every effective key and its source
    python effective.py --key permissions     one subtree, itemized
    python effective.py --problems-only       findings only
    python effective.py --explain KEY         what a key does, and which files may set it
    python effective.py --project DIR         the project to resolve (default: cwd)
    python effective.py --settings FILE|JSON  simulate `claude --settings`
    python effective.py --strict              exit 1 on any error-level finding
    python effective.py --json                everything, machine-readable

Stdlib only. Read-only, always.
"""
from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

# Layers, highest precedence first. The number is the rank used in "shadowed by".
RANK = {"managed": 1, "cli": 2, "local": 3, "project": 4, "user": 5, "global": 6}
LABEL = {"managed": "managed", "cli": "--settings", "local": "local", "project": "project",
         "user": "user", "global": "~/.claude.json"}

# Which layers may set a key, by the Scope column of the settings index.
SCOPE_LAYERS = {
    "Any file": {"managed", "cli", "local", "project", "user"},
    "User, local, or managed": {"managed", "cli", "local", "user"},
    "User or managed": {"managed", "cli", "user"},
    "Managed": {"managed"},
    "Global config": {"global"},
}

# Keys whose value is taken whole from the highest layer rather than merged as a list.
WHOLE_VALUE = {"fallbackModel", "modelPicker"}
# Keys the docs list as read only at session start.
RESTART_ONLY = {"model", "effortLevel", "modelSettings"}
EFFORT_ORDER = ["low", "medium", "high", "xhigh", "max"]
INBOUND_ORDER = ["accept", "hold", "refuse"]

MANAGED_DIRS = {
    "darwin": Path("/Library/Application Support/ClaudeCode"),
    "linux": Path("/etc/claude-code"),
    "win32": Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "ClaudeCode",
}

# --- SETTINGS_INDEX begin
# Generated by docs/update_index.py from https://code.claude.com/docs/en/settings-reference.md on 2026-09-19. Do not edit by hand.
INDEX_DATE = '2026-09-19'
SETTINGS_INDEX: dict[str, tuple[str, str, str]] = {   # key: (scope, topic, description)
    'advisorModel': ('Any file', 'Model and responses', 'Pick which model answers when Claude asks the advisor tool'),
    'agent': ('Any file', 'Agents, sessions, and worktrees', 'Start every session as a named subagent with its prompt, tools, and model'),
    'agentPushNotifEnabled': ('Any file', 'Remote, desktop, and notifications', 'Let Claude send a push notification to your phone when it decides to'),
    'allowAllClaudeAiMcps': ('Managed', 'MCP', 'Load the claude.ai connectors Claude Code fetches itself alongside a deployed managed-mcp.json'),
    'allowManagedHooksOnly': ('Managed', 'Hooks and automation', 'Run only the hooks your organization deploys'),
    'allowManagedMcpServersOnly': ('Managed', 'MCP', 'Make the managed MCP allowlist the only one that applies'),
    'allowManagedPermissionRulesOnly': ('Managed', 'Permission settings', 'Make managed settings the only settings source of permission rules'),
    'allowedChannelPlugins': ('Managed', 'Plugins and skills', 'Replace the default allowlist of channel plugins that can push messages'),
    'allowedHttpHookUrls': ('Any file', 'Hooks and automation', 'Limit which URLs HTTP hooks can target'),
    'allowedMcpServers': ('Any file', 'MCP', 'Allowlist which MCP servers users can add'),
    'alwaysThinkingEnabled': ('Any file', 'Model and responses', 'Turn extended thinking off for every session'),
    'apiKeyHelper': ('Any file', 'Authentication and providers', 'Generate the API credential with your own command'),
    'askUserQuestionTimeout': ('User or managed', 'Interface and terminal', 'Let an unanswered question auto-continue after idle time'),
    'attribution': ('Any file', 'Git and attribution', 'Customize the attribution Claude Code adds to commits and pull requests'),
    'attribution.commit': ('Any file', 'Git and attribution', 'Change or hide the trailer Claude Code adds to commits'),
    'attribution.pr': ('Any file', 'Git and attribution', 'Change or hide the attribution line in pull request descriptions'),
    'attribution.sessionUrl': ('Any file', 'Git and attribution', 'Omit the claude.ai session link from cloud and Remote Control commits'),
    'autoCompactEnabled': ('Any file', 'Memory and context', 'Turn automatic compaction off or on'),
    'autoCompactWindow': ('Any file', 'Memory and context', 'Set how full the context gets before Claude Code compacts'),
    'autoConnectIde': ('Global config', 'Global config settings', 'Connect to a running VS Code or JetBrains IDE automatically from an external terminal'),
    'autoContinueAtUsageLimit': ('User or managed', 'Interface and terminal', 'Wait in the open session and continue the task automatically after a claude.ai usage limit rese…'),
    'autoInstallIdeExtension': ('Global config', 'Global config settings', 'Turn off automatic install of the IDE extension from a VS Code terminal'),
    'autoMemoryDirectory': ('Any file', 'Memory and context', 'Store auto memory in a directory you choose'),
    'autoMemoryEnabled': ('Any file', 'Memory and context', 'Turn auto memory off or on'),
    'autoMode': ('User or managed', 'Permission settings', 'Add your own allow and deny rules to the auto mode classifier'),
    'autoMode.classifyAllShell': ('User or managed', 'Permission settings', 'Send every shell command through the auto mode classifier, even ones a narrow allow rule matches'),
    'autoScrollEnabled': ('Any file', 'Interface and terminal', 'Follow new output to the bottom in fullscreen rendering'),
    'autoUpdatesChannel': ('Any file', 'Updates and versioning', 'Follow the stable release channel instead of latest'),
    'availableModels': ('Any file', 'Model and responses', 'Restrict which models people can pick'),
    'awaySummaryEnabled': ('Any file', 'Remote, desktop, and notifications', 'Turn off the session recap shown when you come back to the terminal'),
    'awsAuthRefresh': ('Any file', 'Authentication and providers', 'Refresh expired Bedrock credentials in .aws with your own command'),
    'awsCredentialExport': ('Any file', 'Authentication and providers', 'Supply Bedrock credentials as JSON from your own command'),
    'axScreenReader': ('Any file', 'Interface and terminal', 'Render screen-reader friendly output'),
    'bashEditDiffEnabled': ('User or managed', 'Interface and terminal', 'Record the files a Bash command changed in every permission mode'),
    'bashOutputMaxChars': ('Any file', 'Memory and context', "Set how much of a successful command's output Claude receives inline"),
    'blockedMarketplaces': ('Managed', 'Plugins and skills', 'Block plugin marketplace sources for your organization'),
    'browserExternalPageTools': ('Managed', 'Tools', "Keep Claude's tools off external pages in the desktop Browser pane"),
    'channelsEnabled': ('Managed', 'Plugins and skills', 'Allow channels for your organization'),
    'claudeMd': ('Managed', 'Memory and context', 'Inject organization-wide CLAUDE.md instructions from managed settings'),
    'claudeMdExcludes': ('Any file', 'Memory and context', 'Skip specific CLAUDE.md files when memory loads'),
    'cleanupPeriodDays': ('Any file', 'Privacy and telemetry', 'Choose how many days Claude Code keeps transcripts before deleting them'),
    'companyAnnouncements': ('Any file', 'Interface and terminal', "Show your organization's announcements at startup"),
    'copyOnSelect': ('Global config', 'Global config settings', 'Turn off automatic copying of text you select with the mouse in fullscreen rendering and agent…'),
    'crossSessionInbound': ('Any file', 'Agents, sessions, and worktrees', 'Choose whether Claude Code delivers messages from your other sessions, shows a notice without d…'),
    'defaultShell': ('Any file', 'Interface and terminal', 'Choose whether Bash or PowerShell runs the shell commands you type with the ! prefix'),
    'deniedMcpServers': ('Any file', 'MCP', 'Block specific MCP servers by URL, command, or name'),
    'desktopSessionCleanupPeriodDays': ('User or managed', 'Privacy and telemetry', 'Set an age limit in days for Claude Desktop and Cowork transcripts'),
    'dialogExpiry': ('User or managed', 'Interface and terminal', 'Set how long Claude Code waits for Remote Control or an SDK host to answer a forwarded dialog b…'),
    'diffTool': ('Global config', 'Global config settings', "Choose whether Claude's proposed file changes open in the VS Code or JetBrains diff viewer or s…"),
    'disableAgentView': ('Any file', 'Agents, sessions, and worktrees', 'Turn off background agents and agent view'),
    'disableAllHooks': ('Any file', 'Hooks and automation', 'Turn off hooks, a custom status line, and a custom @ file suggestion command at once'),
    'disableArtifact': ('Any file', 'Remote, desktop, and notifications', 'Deprecated; use enableArtifact to turn the Artifact tool off'),
    'disableAutoMode': ('Any file', 'Permission settings', 'Remove auto mode from the permission mode cycle'),
    'disableBrowserExternalNavigation': ('Managed', 'Tools', 'Limit the desktop Browser pane to localhost for people and Claude'),
    'disableBundledSkills': ('Any file', 'Plugins and skills', 'Turn off the skills and workflows included with Claude Code'),
    'disableClaudeAiConnectors': ('Any file', 'MCP', "Turn off claude.ai connectors so Claude Code doesn't fetch them"),
    'disableCommandPluginSources': ('Managed', 'Plugins and skills', 'Block plugins that install by running a marketplace-declared command'),
    'disableDeepLinkRegistration': ('Any file', 'Remote, desktop, and notifications', 'Stop Claude Code from registering the claude-cli:// handler'),
    'disableDesktopLocalSessions': ('Managed', 'Remote, desktop, and notifications', 'Turn off Desktop Code sessions that run on the device, leaving SSH to other hosts and cloud'),
    'disableMobileSimulatorTools': ('Managed', 'Tools', "Block Claude's tools in the desktop iOS Simulator pane"),
    'disableRemoteControl': ('Any file', 'Remote, desktop, and notifications', 'Turn off Remote Control everywhere it can start'),
    'disableSideloadFlags': ('Managed', 'Enterprise and managed settings', 'Reject the CLI flags that sideload plugins, subagents, and MCP servers'),
    'disableSkillShellExecution': ('Any file', 'Plugins and skills', 'Stop skills and custom commands from running inline shell'),
    'disableWorkflows': ('Any file', 'Hooks and automation', 'Turn dynamic workflows off for everyone; use enableWorkflows for yourself'),
    'disabledMcpjsonServers': ('Any file', 'MCP', "Reject specific servers from a project's .mcp.json"),
    'editorMode': ('Any file', 'Interface and terminal', 'Use vim key bindings in the input prompt'),
    'effortLevel': ('Any file', 'Model and responses', 'Set a default effort level for models without a saved level of their own'),
    'emojiCompletionEnabled': ('Any file', 'Interface and terminal', 'Turn off :shortcode: emoji suggestions and replacement in the prompt input'),
    'enableAllProjectMcpServers': ('Any file', 'MCP', 'Approve every server in project .mcp.json files without a prompt'),
    'enableArtifact': ('Any file', 'Remote, desktop, and notifications', 'Turn the Artifact tool off with a false in any file; no file can turn it back on'),
    'enableWorkflows': ('Any file', 'Hooks and automation', "Turn dynamic workflows on or off against your plan's default"),
    'enabledMcpjsonServers': ('Any file', 'MCP', "Approve specific servers from a project's .mcp.json"),
    'enabledPlugins': ('Any file', 'Plugins and skills', 'Turn individual plugins on or off per scope'),
    'enforceAvailableModels': ('Any file', 'Model and responses', 'Keep the /model Default choice inside your availableModels allowlist'),
    'env': ('Any file', 'Memory and context', 'Set environment variables for every session and its subprocesses'),
    'externalEditorContext': ('Global config', 'Global config settings', "Show Claude's last response as comments when you press Ctrl+G to edit"),
    'extraKnownMarketplaces': ('Any file', 'Plugins and skills', 'Register marketplaces for a repository or an organization'),
    'fallbackModel': ('Any file', 'Model and responses', 'Name backup models for when the primary is overloaded'),
    'fastMode': ('Any file', 'Model and responses', "Turn fast mode on for sessions where it's available"),
    'fastModePerSessionOptIn': ('Any file', 'Model and responses', 'Require people to turn fast mode on each session'),
    'feedbackDrafts': ('User or managed', 'Privacy and telemetry', 'Control whether Claude queues feedback drafts for you to review'),
    'feedbackSurveyRate': ('Any file', 'Privacy and telemetry', 'Change how often the session quality survey appears'),
    'fileCheckpointingEnabled': ('Any file', 'Memory and context', 'Turn off or on the file snapshots that /rewind restores'),
    'fileSuggestion': ('Any file', 'Interface and terminal', 'Supply @ file autocomplete from your own command'),
    'footerLinksRegexes': ('User or managed', 'Interface and terminal', 'Make issue or review IDs in output into clickable links below the input box'),
    'forceLoginGatewayUrl': ('Managed', 'Authentication and providers', 'Set the gateway URL the login screen connects to'),
    'forceLoginMethod': ('Any file', 'Authentication and providers', 'Restrict login to claude.ai, Claude Console, or a cloud gateway'),
    'forceLoginOrgUUID': ('Any file', 'Authentication and providers', 'Pin claude.ai logins to your organization; only a managed source enforces it'),
    'forceRemoteSettingsRefresh': ('Managed', 'Enterprise and managed settings', 'Block startup until server-managed settings are freshly fetched'),
    'gatewayInternalNetworks': ('Managed', 'Authentication and providers', 'Let /login reach a cloud gateway on public IPv4 space your organization uses internally'),
    'gcpAuthRefresh': ('Any file', 'Authentication and providers', 'Refresh Google Cloud credentials with your own command'),
    'hooks': ('Any file', 'Hooks and automation', "Run your own commands as hooks at points in Claude Code's lifecycle"),
    'httpHookAllowedEnvVars': ('Any file', 'Hooks and automation', 'Limit which env vars HTTP hooks can put in headers'),
    'includeCoAuthoredBy': ('Any file', 'Git and attribution', 'Deprecated; use attribution to hide or change commit and PR attribution'),
    'includeGitInstructions': ('Any file', 'Git and attribution', 'Remove the built-in commit and PR instructions from the system prompt'),
    'inputNeededNotifEnabled': ('Any file', 'Remote, desktop, and notifications', 'Get a push notification when Claude is waiting on you'),
    'isolatePeerMachines': ('Any file', 'Agents, sessions, and worktrees', 'Ask you before Claude messages one of your sessions on another machine'),
    'keybindingFlavor': ('Any file', 'Interface and terminal', 'Deprecated and has no effect; the word-editing shortcuts always follow readline conventions'),
    'language': ('Any file', 'Model and responses', 'Have Claude respond in a language other than English'),
    'managedMcpServers': ('Managed', 'MCP', 'Provide remote MCP servers to every user alongside the ones they add'),
    'managedSourcesBehavior': ('Managed', 'Enterprise and managed settings', 'Compose every managed source you deploy instead of using the highest-priority one alone'),
    'maxEffortLevel': ('Any file', 'Model and responses', 'Cap the effort level for every model or per model, on every provider'),
    'minimumVersion': ('Any file', 'Updates and versioning', 'Keep auto-updates from installing anything below a version'),
    'model': ('Any file', 'Model and responses', 'Change the model Claude Code starts with'),
    'modelOverrides': ('Any file', 'Model and responses', "Map model IDs to your provider's IDs, such as Bedrock ARNs"),
    'modelPicker': ('User or managed', 'Model and responses', 'Choose which models the /model picker lists, in your own order and with your own labels'),
    'modelPricing': ('Managed', 'Model and responses', "Report spend at your organization's contracted rates instead of list price"),
    'modelSettings': ('Any file', 'Model and responses', "Keep a saved effort level per model, or cap one model's effort"),
    'otelHeadersHelper': ('Any file', 'Authentication and providers', 'Generate rotating OpenTelemetry headers with your own command'),
    'outputStyle': ('Any file', 'Model and responses', "Change Claude's role, tone, and output format with an output style"),
    'parentSettingsBehavior': ('Managed', 'Enterprise and managed settings', 'Apply or drop restrictions an SDK or IDE host passes when you deploy managed settings'),
    'permissionExplainerEnabled': ('Global config', 'Global config settings', 'Removed in v2.1.257, together with the Ctrl+E command explanation on shell permission prompts'),
    'permissions': ('Any file', 'Permission settings', 'Set allow, ask, and deny rules and the starting permission mode'),
    'permissions.additionalDirectories': ('Any file', 'Permission settings', 'Give Claude file access to directories outside the current one'),
    'permissions.allow': ('Any file', 'Permission settings', 'Approve listed tool uses without a prompt'),
    'permissions.ask': ('Any file', 'Permission settings', 'Always prompt before listed tool uses'),
    'permissions.blockReadsOutsideWorkingDirectories': ('Any file', 'Permission settings', 'Make the file tools refuse reads outside the working directories in every permission mode'),
    'permissions.defaultMode': ('Any file', 'Permission settings', 'Set the permission mode new sessions start in'),
    'permissions.deny': ('Any file', 'Permission settings', 'Block listed tool uses, including reads of files that hold secrets'),
    'permissions.disableBypassPermissionsMode': ('Any file', 'Permission settings', 'Prevent anyone from entering bypassPermissions mode'),
    'plansDirectory': ('Any file', 'Memory and context', 'Choose where plan mode writes plan files'),
    'pluginConfigs': ('User or managed', 'Plugins and skills', "Store the answers you gave a plugin's configuration dialog"),
    'pluginSuggestionMarketplaces': ('Managed', 'Plugins and skills', 'Choose which marketplaces can surface plugin install suggestions in /plugin'),
    'pluginTrustMessage': ('Managed', 'Plugins and skills', 'Add your own text to the plugin trust warning'),
    'policyHelper': ('Managed', 'Enterprise and managed settings', 'Run an executable that computes managed settings at startup'),
    'policyHelper.path': ('Managed', 'Enterprise and managed settings', 'Name the helper executable Claude Code runs'),
    'policyHelper.refreshIntervalMs': ('Managed', 'Enterprise and managed settings', 'Re-run the helper in the background on an interval'),
    'policyHelper.timeoutMs': ('Managed', 'Enterprise and managed settings', 'Set how long Claude Code waits for the helper'),
    'prUrlTemplate': ('Any file', 'Git and attribution', 'Point PR links at an internal code-review tool instead of github.com'),
    'preferredNotifChannel': ('Any file', 'Remote, desktop, and notifications', 'Choose a terminal bell or desktop notification for task completion'),
    'prefersReducedMotion': ('Any file', 'Interface and terminal', 'Reduce or turn off spinner, shimmer, and flash animations'),
    'processWrapper': ('User or managed', 'Agents, sessions, and worktrees', "Run Claude Code's background processes through a corporate launcher on macOS and Linux"),
    'promptCacheTtl': ('Any file', 'Model and responses', 'Choose the prompt cache lifetime for the main conversation'),
    'promptSuggestionEnabled': ('Any file', 'Interface and terminal', 'Hide the grayed-out prompt suggestions in the input box'),
    'remote.defaultEnvironmentId': ('Any file', 'Remote, desktop, and notifications', 'Pick the default cloud environment for claude --cloud; a self-hosted ccpool_ ID is read only fr…'),
    'remoteControlAtStartup': ('Any file', 'Remote, desktop, and notifications', 'Connect Remote Control automatically when a session starts'),
    'requiredMaximumVersion': ('Managed', 'Updates and versioning', 'Refuse to start on a version newer than your organization allows'),
    'requiredMinimumVersion': ('Managed', 'Updates and versioning', 'Refuse to start on a version older than your organization requires'),
    'respectGitignore': ('Any file', 'Interface and terminal', 'Keep gitignored files out of the @ file picker'),
    'respondToBashCommands': ('Any file', 'Interface and terminal', 'Stop Claude from responding after a ! shell command runs'),
    'sandbox': ('Any file', 'Sandbox settings', 'Isolate Bash commands from your filesystem and network on macOS, Linux, and WSL2'),
    'sandbox.allowAppleEvents': ('User or managed', 'Sandbox settings', 'Let sandboxed commands send Apple Events on macOS'),
    'sandbox.allowUnsandboxedCommands': ('Any file', 'Sandbox settings', 'Let Claude retry a blocked command outside the sandbox, or forbid it'),
    'sandbox.autoAllowBashIfSandboxed': ('Any file', 'Sandbox settings', 'Run sandboxed commands without a permission prompt'),
    'sandbox.bwrapPath': ('Managed', 'Sandbox settings', 'Point the sandbox at a bubblewrap binary outside PATH'),
    'sandbox.credentials': ('Any file', 'Sandbox settings', 'Hide or mask credential files and variables inside the sandbox'),
    'sandbox.credentials.allowPlaintextInject': ('User or managed', 'Sandbox settings', 'Let masked credentials reach plain HTTP services on trusted test networks'),
    'sandbox.credentials.awsPairs': ('User or managed', 'Sandbox settings', 'Link custom-named AWS key variables into one credential for re-signing'),
    'sandbox.credentials.envVars': ('Any file', 'Sandbox settings', 'Unset or mask an environment variable inside the sandbox'),
    'sandbox.credentials.files': ('Any file', 'Sandbox settings', 'Block or mask reads of a credential file inside the sandbox'),
    'sandbox.credentials.sigv4': ('User or managed', 'Sandbox settings', 'Choose whether streaming, presigned, or SigV4A AWS requests fail or pass through'),
    'sandbox.enableWeakerNestedSandbox': ('Any file', 'Sandbox settings', 'Run the Linux sandbox inside an unprivileged container'),
    'sandbox.enableWeakerNetworkIsolation': ('Any file', 'Sandbox settings', 'Let gh, gcloud, and terraform verify TLS behind a MITM proxy inside the sandbox on macOS'),
    'sandbox.enabled': ('Any file', 'Sandbox settings', 'Turn on Bash sandboxing on macOS, Linux, and WSL2'),
    'sandbox.excludedCommands': ('Any file', 'Sandbox settings', 'Name commands that always run outside the sandbox'),
    'sandbox.failIfUnavailable': ('Any file', 'Sandbox settings', "Refuse to start when the sandbox can't, instead of running unsandboxed"),
    'sandbox.filesystem': ('Any file', 'Sandbox settings', 'Control which paths sandboxed commands can read and write'),
    'sandbox.filesystem.allowManagedReadPathsOnly': ('Managed', 'Sandbox settings', 'Stop developers from re-opening read paths your organization blocked'),
    'sandbox.filesystem.allowRead': ('Any file', 'Sandbox settings', 'Re-open reading inside a region denyRead blocks'),
    'sandbox.filesystem.allowWrite': ('Any file', 'Sandbox settings', 'Add paths sandboxed commands can write to'),
    'sandbox.filesystem.denyRead': ('Any file', 'Sandbox settings', 'Block sandboxed commands from reading specific paths'),
    'sandbox.filesystem.denyWrite': ('Any file', 'Sandbox settings', 'Block sandboxed commands from writing to specific paths'),
    'sandbox.filesystem.disabled': ('User or managed', 'Sandbox settings', 'Turn off filesystem isolation while keeping network isolation'),
    'sandbox.ignoreViolations': ('Any file', 'Sandbox settings', 'Silence violation reports for paths a command is expected to probe'),
    'sandbox.network': ('Any file', 'Sandbox settings', 'Control which hosts, ports, and sockets sandboxed commands reach'),
    'sandbox.network.allowAllUnixSockets': ('Any file', 'Sandbox settings', 'Let sandboxed commands connect to every Unix socket'),
    'sandbox.network.allowLocalBinding': ('Any file', 'Sandbox settings', 'Let sandboxed commands bind to localhost ports on macOS'),
    'sandbox.network.allowMachLookup': ('Any file', 'Sandbox settings', 'Let macOS sandboxed tools like the iOS Simulator or Playwright reach their XPC services'),
    'sandbox.network.allowManagedDomainsOnly': ('Managed', 'Sandbox settings', 'Lock the network allowlist to managed settings'),
    'sandbox.network.allowUnixSockets': ('Any file', 'Sandbox settings', 'List Unix socket paths sandboxed commands can use on macOS'),
    'sandbox.network.allowedDomains': ('Any file', 'Sandbox settings', "Pre-allow domains so sandboxed commands don't prompt for them"),
    'sandbox.network.deniedDomains': ('Any file', 'Sandbox settings', 'Block domains for sandboxed commands, even inside an allowed wildcard'),
    'sandbox.network.httpProxyPort': ('Any file', 'Sandbox settings', 'Route sandbox HTTP traffic through your own proxy'),
    'sandbox.network.socksProxyPort': ('Any file', 'Sandbox settings', 'Route sandbox SOCKS traffic through your own proxy'),
    'sandbox.network.strictAllowlist': ('User or managed', 'Sandbox settings', 'Deny hosts outside the allowlist instead of prompting'),
    'sandbox.network.tlsTerminate': ('User or managed', 'Sandbox settings', 'Have the sandbox proxy terminate TLS so it can read HTTPS requests'),
    'sandbox.ripgrep': ('User or managed', 'Sandbox settings', 'Use your own ripgrep binary inside the sandbox'),
    'sandbox.socatPath': ('Managed', 'Sandbox settings', 'Point the sandbox proxy at a socat binary outside PATH'),
    'showClearContextOnPlanAccept': ('Any file', 'Interface and terminal', 'Show a "clear context" option on the plan accept screen'),
    'showThinkingSummaries': ('Any file', 'Model and responses', "See summaries of Claude's thinking instead of a collapsed stub"),
    'showTurnDuration': ('Any file', 'Interface and terminal', 'Hide the "Cooked for" duration after each response'),
    'skillListingBudgetFraction': ('Any file', 'Memory and context', 'Reserve more or less context for the skill listing'),
    'skillListingMaxDescChars': ('Any file', 'Memory and context', "Cap each skill's description length in the skill listing"),
    'skillOverrides': ('Any file', 'Plugins and skills', 'Hide or collapse a skill without editing its SKILL.md'),
    'skipAutoPermissionPrompt': ('User or managed', 'Permission settings', 'Skip the one-time notice Claude Code shows when you first enter auto mode yourself rather than…'),
    'skipDangerousModePermissionPrompt': ('User, local, or managed', 'Permission settings', 'Skip the confirmation dialog before bypassPermissions mode'),
    'skipWebFetchPreflight': ('Any file', 'Privacy and telemetry', 'Skip the WebFetch hostname check when Anthropic is unreachable'),
    'spellcheck': ('User or managed', 'Interface and terminal', 'Underline misspelled words in the prompt input with a spell checker you install'),
    'spinnerTipsEnabled': ('Any file', 'Interface and terminal', 'Hide tips in the spinner while Claude works'),
    'spinnerTipsOverride': ('Any file', 'Interface and terminal', 'Add your own tips to the spinner rotation, or replace the built-in tips'),
    'spinnerVerbs': ('Any file', 'Interface and terminal', 'Add or replace the verbs shown while a turn runs'),
    'sshConfigs': ('User or managed', 'Remote, desktop, and notifications', 'Add SSH connections to the Desktop environment dropdown'),
    'sshHostAllowlist': ('Managed', 'Remote, desktop, and notifications', 'Limit which hosts Desktop SSH sessions can reach'),
    'statusLine': ('Any file', 'Interface and terminal', 'Run your own command to render a status line below the prompt'),
    'strictKnownMarketplaces': ('Managed', 'Plugins and skills', 'Allowlist the marketplace sources users can add and install from'),
    'strictPluginOnlyCustomization': ('Managed', 'Plugins and skills', 'Block skills, agents, hooks, and MCP servers from user and project sources'),
    'strictPluginOnlyCustomization.agents': ('Managed', 'Plugins and skills', 'Lock agents to plugin and managed sources'),
    'strictPluginOnlyCustomization.hooks': ('Managed', 'Plugins and skills', 'Lock hooks to plugin and managed sources'),
    'strictPluginOnlyCustomization.mcp': ('Managed', 'Plugins and skills', 'Lock MCP servers to plugin and managed sources'),
    'strictPluginOnlyCustomization.skills': ('Managed', 'Plugins and skills', 'Lock skills to plugin and managed sources'),
    'subagentPromptCacheTtl': ('Any file', 'Model and responses', 'Choose the prompt cache lifetime for subagents and other requests outside the main conversation'),
    'subagentStatusLine': ('Any file', 'Interface and terminal', 'Rewrite rows in the subagent task display with your own command'),
    'switchModelsOnFlag': ('Any file', 'Model and responses', 'Switch models automatically or pause when a safety classifier flags a request'),
    'syncClaudeAiPlugins': ('User, local, or managed', 'Plugins and skills', 'Stop loading the plugins enabled on your claude.ai account and stop downloading new ones'),
    'syncClaudeAiSkills': ('User, local, or managed', 'Plugins and skills', 'Stop loading the skills enabled on your claude.ai account and stop downloading new ones'),
    'syntaxHighlightingDisabled': ('Any file', 'Interface and terminal', 'Turn off syntax highlighting in diffs and code blocks'),
    'taskOutputMaxChars': ('Any file', 'Memory and context', "Set how much of a background task's output Claude receives inline"),
    'teammateDefaultModel': ('Global config', 'Global config settings', "Removed in v2.1.234; see Specify teammates and models for how Claude Code picks a teammate's mo…"),
    'teammateMode': ('Any file', 'Agents, sessions, and worktrees', 'Choose how agent team teammates display'),
    'terminalProgressBarEnabled': ('Any file', 'Interface and terminal', 'Hide the terminal progress bar in terminals that support it'),
    'terminalTitleFromRename': ('Any file', 'Interface and terminal', 'Stop /rename and --name from changing the terminal tab title'),
    'theme': ('Any file', 'Interface and terminal', 'Pick the interface color theme, built-in or custom'),
    'timeFormat': ('Any file', 'Interface and terminal', 'Show the times in the interface on a 12-hour or 24-hour clock, in UTC, or with a strftime patte…'),
    'timeZone': ('Any file', 'Interface and terminal', "Show the times in the interface in a time zone other than your system's"),
    'tui': ('Any file', 'Interface and terminal', 'Choose the fullscreen or classic terminal renderer'),
    'ultracode': ('Any file', 'Model and responses', 'Have Claude plan a workflow for each substantive task without being asked'),
    'useAutoModeDuringPlan': ('User, local, or managed', 'Permission settings', 'Let the auto mode classifier review shell commands in plan mode; set false to get prompts inste…'),
    'verbose': ('Any file', 'Interface and terminal', 'Show full tool output instead of truncated summaries; viewMode takes precedence when both are s…'),
    'viewMode': ('Any file', 'Interface and terminal', 'Start every session in default, verbose, or focus view'),
    'vimInsertModeRemaps': ('User or managed', 'Interface and terminal', 'Map a two-key INSERT-mode sequence such as jj to Escape'),
    'voice': ('Any file', 'Interface and terminal', 'Turn on voice dictation and pick hold or tap mode'),
    'voiceEnabled': ('Any file', 'Interface and terminal', 'Turn on voice dictation with the older single-key form'),
    'wheelScrollAccelerationEnabled': ('Any file', 'Interface and terminal', 'Turn off mouse-wheel acceleration in fullscreen rendering'),
    'workflowKeywordTriggerEnabled': ('Any file', 'Hooks and automation', 'Let the word ultracode in a prompt start a workflow; set false to type it without starting one'),
    'workflowSizeGuideline': ('Any file', 'Hooks and automation', 'Set the agent count Claude aims for in dynamic workflows'),
    'worktree': ('Any file', 'Agents, sessions, and worktrees', 'Configure how Claude Code creates git worktrees'),
    'worktree.baseRef': ('Any file', 'Agents, sessions, and worktrees', 'Branch new worktrees from the remote default branch or your local HEAD'),
    'worktree.bgIsolation': ('Any file', 'Agents, sessions, and worktrees', 'Let background sessions edit the working copy without a worktree'),
    'worktree.sparsePaths': ('Any file', 'Agents, sessions, and worktrees', 'Check out only the directories you need in each worktree'),
    'worktree.symlinkDirectories': ('Any file', 'Agents, sessions, and worktrees', 'Symlink large directories into each worktree instead of duplicating them'),
    'wslInheritsWindowsSettings': ('Managed', 'Enterprise and managed settings', 'Have WSL read managed settings from the Windows policy chain'),
}
# --- SETTINGS_INDEX end


# --------------------------------------------------------------------------- model

@dataclass
class Layer:
    name: str                 # managed | cli | local | project | user | global
    path: str
    data: dict = field(default_factory=dict)
    present: bool = False
    error: str = ""           # invalid JSON etc. -> the file is skipped, like the harness does


@dataclass
class Entry:
    key: str                  # dotted leaf path, e.g. permissions.allow, env.FOO
    value: Any
    source: str               # layer name that decided it (or "merged" for lists)
    sources: list[str] = field(default_factory=list)   # for lists: layer per element, aligned
    shadowed: list[dict] = field(default_factory=list)  # [{layer, value}] that lost


@dataclass
class Finding:
    severity: str             # error | warn | info
    key: str
    layer: str
    message: str


@dataclass
class Report:
    project: str
    layers: list[Layer] = field(default_factory=list)
    trusted: bool | None = None
    legacy_allowed_tools: list[str] = field(default_factory=list)
    entries: list[Entry] = field(default_factory=list)
    findings: list[Finding] = field(default_factory=list)
    index_date: str = INDEX_DATE


# --------------------------------------------------------------------------- loading

def read_json(p: Path) -> tuple[dict, str]:
    try:
        text = p.read_text(encoding="utf-8-sig")
    except FileNotFoundError:
        return {}, ""
    except OSError as e:
        return {}, f"unreadable: {e.strerror}"
    try:
        d = json.loads(text)
    except ValueError as e:
        return {}, f"invalid JSON: {e}"
    if not isinstance(d, dict):
        return {}, "top level is not an object"
    return d, ""


def project_dir(start: Path) -> Path:
    """cwd if it has a .claude/, else the nearest ancestor with one, else cwd."""
    start = start.resolve()
    for p in [start, *start.parents]:
        if (p / ".claude").is_dir():
            return p
        if (p / ".git").exists():
            break
    return start


def managed_layer(managed_dir: Path) -> Layer:
    base = managed_dir / "managed-settings.json"
    dropins = sorted(p for p in (managed_dir / "managed-settings.d").glob("*.json")
                     if not p.name.startswith(".")) if (managed_dir / "managed-settings.d").is_dir() else []
    layer = Layer("managed", str(base))
    parts: list[tuple[Path, dict]] = []
    errors = []
    for p in [base, *dropins]:
        d, err = read_json(p)
        if err:
            errors.append(f"{p.name}: {err}")
        elif p.exists():
            parts.append((p, d))
    if not parts and not errors:
        return layer
    layer.present = bool(parts)
    layer.error = "; ".join(errors)
    merged: dict = {}
    for _, d in parts:                       # file first, then drop-ins alphabetically
        merged = merge_two(merged, d)
    layer.data = merged
    if dropins:
        layer.path = f"{base} + managed-settings.d/ ({len(dropins)})"
    return layer


def cli_layer(arg: str | None) -> Layer:
    layer = Layer("cli", "--settings")
    if not arg:
        return layer
    p = Path(arg)
    if p.is_file():
        layer.path = f"--settings {p}"
        layer.data, layer.error = read_json(p)
        layer.present = not layer.error
    else:
        try:
            d = json.loads(arg)
            layer.data, layer.present = (d if isinstance(d, dict) else {}), isinstance(d, dict)
            layer.path = "--settings (inline JSON)"
            if not layer.present:
                layer.error = "top level is not an object"
        except ValueError as e:
            layer.error = f"invalid JSON: {e}"
    return layer


def file_layer(name: str, p: Path) -> Layer:
    layer = Layer(name, str(p))
    layer.data, layer.error = read_json(p)
    layer.present = p.exists() and not layer.error
    return layer


def global_layer(claude_json: Path) -> tuple[Layer, dict]:
    """Only the index's 'Global config' keys count as settings; the rest is state."""
    raw, err = read_json(claude_json)
    layer = Layer("global", str(claude_json))
    layer.error = err
    layer.present = bool(raw) and not err
    layer.data = {k: v for k, v in raw.items()
                  if SETTINGS_INDEX.get(k, ("",))[0] == "Global config"}
    return layer, raw


# --------------------------------------------------------------------------- merging

def merge_two(low: dict, high: dict) -> dict:
    """high wins per leaf; lists union; objects recurse."""
    out = dict(low)
    for k, v in high.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = merge_two(out[k], v)
        elif k in out and isinstance(out[k], list) and isinstance(v, list) and k not in WHOLE_VALUE:
            out[k] = out[k] + [x for x in v if x not in out[k]]
        else:
            out[k] = v
    return out


def leaves(d: dict, prefix: str = "") -> list[tuple[str, Any]]:
    out = []
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict) and v and not _atomic(key):
            out.extend(leaves(v, key))
        else:
            out.append((key, v))
    return out


def _atomic(key: str) -> bool:
    # Objects that are one value, not a bag of keys: mixing statusLine.type from one
    # file with statusLine.command from another would describe nothing real.
    return key.split(".")[0] in ("statusLine", "agent", "modelPicker")


def top_key(key: str) -> str:
    return key.split(".")[0]


def index_scope(key: str) -> str | None:
    """Scope for the most specific index entry covering this dotted key."""
    parts = key.split(".")
    while parts:
        hit = SETTINGS_INDEX.get(".".join(parts))
        if hit:
            return hit[0]
        parts.pop()
    return None


def resolve(layers: list[Layer], findings: list[Finding]) -> list[Entry]:
    """Walk layers from lowest to highest precedence, recording who set each leaf."""
    by_layer = {l.name: l for l in layers}
    order = sorted((l for l in layers if l.present), key=lambda l: -RANK[l.name])  # user -> managed
    table: dict[str, Entry] = {}
    for layer in order:
        for key, value in leaves(layer.data):
            allowed = SCOPE_LAYERS.get(index_scope(key) or "Any file", SCOPE_LAYERS["Any file"])
            if layer.name not in allowed:
                scope = index_scope(key)
                findings.append(Finding("error", key, layer.name,
                                        f"ignored here: scope is '{scope}', set it in "
                                        f"{' / '.join(LABEL[x] for x in sorted(allowed, key=RANK.get))}"))
                continue
            if top_key(key) not in SETTINGS_INDEX and index_scope(key) is None and layer.name != "global":
                near = difflib.get_close_matches(top_key(key), SETTINGS_INDEX, n=1, cutoff=0.75)
                hint = f" - did you mean '{near[0]}'?" if near else ""
                findings.append(Finding("warn", key, layer.name, f"not a known settings key{hint}"))
            prev = table.get(key)
            if prev is None:
                table[key] = Entry(key, value, layer.name,
                                   [layer.name] * len(value) if isinstance(value, list) else [])
            elif isinstance(prev.value, list) and isinstance(value, list) and top_key(key) not in WHOLE_VALUE:
                for x in value:
                    if x not in prev.value:
                        prev.value.append(x)
                        prev.sources.append(layer.name)
                    else:
                        findings.append(Finding("info", key, layer.name,
                                                f"{json.dumps(x)} already listed by {LABEL[prev.sources[prev.value.index(x)]]}"))
                prev.source = "merged" if len(set(prev.sources)) > 1 else prev.source
            else:
                if prev.value != value:
                    prev.shadowed.append({"layer": prev.source, "value": prev.value})
                    findings.append(Finding("info", key, prev.source,
                                            f"{LABEL[prev.source]} sets {json.dumps(prev.value)[:40]} but "
                                            f"{LABEL[layer.name]} wins with {json.dumps(value)[:40]}"))
                prev.value, prev.source = value, layer.name
                prev.sources = [layer.name] * len(value) if isinstance(value, list) else []
    apply_strict_exceptions(table, layers, findings)
    return [table[k] for k in sorted(table)]


def apply_strict_exceptions(table: dict[str, Entry], layers: list[Layer], findings: list[Finding]) -> None:
    """The docs' 'stricter value from a lower scope wins' table."""
    vals = {l.name: dict(leaves(l.data)) for l in layers if l.present}

    def honor(key: str, from_layers: set[str], pick) -> None:
        cands = [(n, v[key]) for n, v in vals.items() if key in v and n in from_layers]
        if not cands or key not in table:
            return
        winner = pick(cands)
        if winner and winner[1] != table[key].value:
            e = table[key]
            # the plain "X wins" note for this key is wrong now; the exception reverses it
            findings[:] = [f for f in findings if not (f.key == key and f.layer == winner[0] and "wins with" in f.message)]
            findings.append(Finding("info", key, winner[0],
                                    f"security key: {LABEL[winner[0]]}'s stricter {json.dumps(winner[1])} is honored over "
                                    f"{LABEL[e.source]}'s {json.dumps(e.value)}"))
            e.shadowed.append({"layer": e.source, "value": e.value})
            e.value, e.source = winner[1], winner[0]

    anyf = {"managed", "cli", "local", "project", "user"}
    honor("disableClaudeAiConnectors", anyf, lambda c: next((x for x in c if x[1] is True), None))
    honor("isolatePeerMachines", anyf, lambda c: next((x for x in c if x[1] is True), None))
    honor("enableArtifact", anyf, lambda c: next((x for x in c if x[1] is False), None))
    honor("disableArtifact", anyf, lambda c: next((x for x in c if x[1] is True), None))
    honor("remoteControlAtStartup", {"project", "local"}, lambda c: next((x for x in c if x[1] is False), None))
    for k in ("useAutoModeDuringPlan", "syncClaudeAiSkills", "syncClaudeAiPlugins"):
        honor(k, {"managed", "cli", "user", "local"}, lambda c: next((x for x in c if x[1] is False), None))
    honor("maxEffortLevel", anyf,
          lambda c: min((x for x in c if x[1] in EFFORT_ORDER), key=lambda x: EFFORT_ORDER.index(x[1]), default=None))
    honor("crossSessionInbound", {"project", "local"},
          lambda c: max((x for x in c if x[1] in INBOUND_ORDER), key=lambda x: INBOUND_ORDER.index(x[1]), default=None))


# --------------------------------------------------------------------------- permissions

RULE = re.compile(r"^(?P<tool>[A-Za-z_][\w-]*)(?:\((?P<spec>.*)\))?$")


def permission_findings(entries: dict[str, Entry], findings: list[Finding], trusted: bool | None) -> None:
    lists = {k: entries.get(f"permissions.{k}") for k in ("allow", "ask", "deny")}
    deny = set(lists["deny"].value) if lists["deny"] else set()
    ask = set(lists["ask"].value) if lists["ask"] else set()
    if lists["allow"]:
        for rule, src in zip(lists["allow"].value, lists["allow"].sources):
            if rule in deny:
                findings.append(Finding("warn", "permissions.allow", src,
                                        f"{json.dumps(rule)} is allowed here but denied elsewhere - deny wins"))
            elif rule in ask:
                findings.append(Finding("warn", "permissions.allow", src,
                                        f"{json.dumps(rule)} is allowed here but an ask rule for it exists - ask wins, you will still be prompted"))
            if not RULE.match(rule):
                findings.append(Finding("warn", "permissions.allow", src, f"{json.dumps(rule)} is not Tool or Tool(spec) shaped"))
        if trusted is False and any(s == "project" for s in lists["allow"].sources):
            findings.append(Finding("warn", "permissions.allow", "project",
                                    "project allow rules apply only after you trust this folder; it is not trusted yet"))
    for k in ("ask", "deny"):
        e = lists[k]
        if e:
            for rule, src in zip(e.value, e.sources):
                if not RULE.match(rule):
                    findings.append(Finding("warn", f"permissions.{k}", src, f"{json.dumps(rule)} is not Tool or Tool(spec) shaped"))
    mode = entries.get("permissions.defaultMode")
    if mode and mode.value == "bypassPermissions":
        dis = entries.get("permissions.disableBypassPermissionsMode")
        if dis and dis.value == "disable":
            findings.append(Finding("warn", "permissions.defaultMode", mode.source,
                                    f"bypassPermissions requested but {LABEL[dis.source]} disables bypass mode"))


# --------------------------------------------------------------------------- hooks / env

def hook_rows(entries: list[Entry]) -> list[tuple[str, str, str, str]]:
    """(event, matcher, command-or-type, source) for every hook handler."""
    rows = []
    for e in entries:
        if not e.key.startswith("hooks.") or not isinstance(e.value, list):
            continue
        event = e.key.split(".", 1)[1]
        for group, src in zip(e.value, e.sources):
            if not isinstance(group, dict):
                continue
            matcher = group.get("matcher", "*") or "*"
            for h in group.get("hooks", []) or []:
                if isinstance(h, dict):
                    what = h.get("command") or h.get("url") or h.get("prompt") or h.get("type", "?")
                    rows.append((event, str(matcher), str(what), src))
    return rows


def env_findings(entries: dict[str, Entry], findings: list[Finding], trusted: bool | None) -> None:
    for e in entries.values():
        if not e.key.startswith("env."):
            continue
        var = e.key[4:]
        shell = os.environ.get(var)
        if shell is not None and str(shell) != str(e.value):
            findings.append(Finding("info", e.key, e.source,
                                    f"also exported in your shell as {json.dumps(shell)[:40]}; which applies is decided per variable"))
        if trusted is False and e.source == "project":
            findings.append(Finding("warn", e.key, "project", "project env applies only after you trust this folder"))


# --------------------------------------------------------------------------- report

def short(v: Any, width: int) -> str:
    s = v if isinstance(v, str) and v.strip() else json.dumps(v, ensure_ascii=False)
    return s if len(s) <= width else s[: width - 1] + "…"


def render(rep: Report, a) -> None:
    W = 200 if a.full else 48
    print(f"settings-effective  {rep.project}")
    print()
    for l in sorted(rep.layers, key=lambda l: RANK[l.name]):
        state = "loaded" if l.present else ("SKIPPED" if l.error else "absent")
        line = f"  {LABEL[l.name]:15} {state:8} {l.path}"
        if l.error:
            line += f"   <- {l.error}"
        print(line)
    if rep.trusted is None:
        print(f"  {'trust':15} {'unknown':8} no entry for this project in ~/.claude.json (never opened here?)")
    else:
        print(f"  {'trust':15} {'yes' if rep.trusted else 'NO':8} ~/.claude.json projects entry"
              + ("" if rep.trusted else "   <- project allow rules, env and marketplaces wait for trust"))
    if rep.legacy_allowed_tools:
        print(f"  {'allowedTools':15} {len(rep.legacy_allowed_tools):<8} legacy per-project allow list in ~/.claude.json")
    if rep.index_date:
        print(f"  {'index':15} {'':8} {len(SETTINGS_INDEX)} keys from the docs, {rep.index_date}")

    entries = rep.entries
    if a.key:
        entries = [e for e in entries if e.key == a.key or e.key.startswith(a.key + ".")]
    if not a.problems_only:
        print()
        if not entries:
            print("  (no effective keys" + (f" under {a.key}" if a.key else "") + ")")
        for e in entries:
            if isinstance(e.value, list):
                itemize = a.full or a.key or e.key.startswith(("permissions.", "hooks."))
                if itemize and not e.key.startswith("hooks."):
                    print(f"  {e.key:44} [{len(e.value)}]")
                    for v, s in zip(e.value, e.sources):
                        print(f"    {short(v, W + 30):74}  {LABEL[s]}")
                else:
                    srcs = ", ".join(LABEL[s] for s in dict.fromkeys(e.sources))
                    n = len(e.value)
                    count = f"[{n} {'entry' if n == 1 else 'entries'}]"
                    print(f"  {e.key:44} {count:{W}}  {srcs}")
            else:
                print(f"  {e.key:44} {short(e.value, W):{W}}  {LABEL[e.source]}")
        rows = hook_rows(entries)
        if rows:
            print()
            print(f"hooks     {len(rows)} handler{'s' if len(rows) != 1 else ''}")
            for ev, m, what, src in rows:
                print(f"  {ev:20} {m:24} {short(what, 60):60}  {LABEL[src]}")

    fs = rep.findings
    if a.key:
        fs = [f for f in fs if f.key == a.key or f.key.startswith(a.key + ".")]
    sev = {"error": 0, "warn": 0, "info": 0}
    for f in fs:
        sev[f.severity] += 1
    print()
    print(f"findings  {sev['error']} ignored, {sev['warn']} warnings, {sev['info']} notes")
    for f in sorted(fs, key=lambda f: ({"error": 0, "warn": 1, "info": 2}[f.severity], f.key)):
        tag = {"error": "IGNORED", "warn": "warn", "info": "note"}[f.severity]
        print(f"  {tag:8} {f.key:40} {LABEL.get(f.layer, f.layer):12} {f.message}")


def explain(key: str) -> int:
    hit = SETTINGS_INDEX.get(key)
    if not hit:
        near = difflib.get_close_matches(key, SETTINGS_INDEX, n=5, cutoff=0.5)
        print(f"{key}: not in the settings index" + (f"; near: {', '.join(near)}" if near else ""))
        return 1
    scope, topic, desc = hit
    layers = SCOPE_LAYERS.get(scope, set())
    print(f"{key}")
    print(f"  {desc}")
    print(f"  topic   {topic}")
    print(f"  scope   {scope}  ->  {', '.join(LABEL[x] for x in sorted(layers, key=RANK.get))}")
    if key in WHOLE_VALUE:
        print("  merge   taken whole from the highest layer that sets it (not merged as a list)")
    if key in RESTART_ONLY:
        print("  note    read at session start; an edit does not reach a running session")
    subs = [k for k in SETTINGS_INDEX if k.startswith(key + ".")]
    if subs:
        print(f"  subkeys {', '.join(subs)}")
    return 0


# --------------------------------------------------------------------------- main

def build(a) -> Report:
    claude_home = Path(a.claude_home)
    proj = project_dir(Path(a.project))
    rep = Report(project=str(proj))
    managed_dir = Path(a.managed_dir) if a.managed_dir else MANAGED_DIRS.get(sys.platform, MANAGED_DIRS["linux"])
    glayer, raw_global = global_layer(Path(a.claude_json) if a.claude_json else Path.home() / ".claude.json")
    rep.layers = [
        managed_layer(managed_dir),
        cli_layer(a.settings),
        file_layer("local", proj / ".claude" / "settings.local.json"),
        file_layer("project", proj / ".claude" / "settings.json"),
        file_layer("user", claude_home / "settings.json"),
        glayer,
    ]
    pentry = (raw_global.get("projects") or {}).get(str(proj)) or {}
    if not pentry:                                  # the harness keys this by the path it saw
        for k, v in (raw_global.get("projects") or {}).items():
            try:
                if Path(k).resolve() == proj:
                    pentry = v
                    break
            except OSError:
                pass
    if pentry:
        rep.trusted = bool(pentry.get("hasTrustDialogAccepted"))
        rep.legacy_allowed_tools = list(pentry.get("allowedTools") or [])
    for l in rep.layers:
        if l.error:
            rep.findings.append(Finding("error", "(file)", l.name, f"{l.error} - the whole file is skipped"))
    rep.entries = resolve(rep.layers, rep.findings)
    by_key = {e.key: e for e in rep.entries}
    permission_findings(by_key, rep.findings, rep.trusted)
    env_findings(by_key, rep.findings, rep.trusted)
    for e in rep.entries:
        if top_key(e.key) in RESTART_ONLY:
            rep.findings.append(Finding("info", e.key, e.source, "read at session start only; use /model or /effort to change it mid-session"))
    if by_key.get("disableAllHooks", Entry("", False, "")).value is True and any(e.key.startswith("hooks.") for e in rep.entries):
        rep.findings.append(Finding("warn", "hooks", by_key["disableAllHooks"].source, "disableAllHooks is true - none of the hooks below run"))
    return rep


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", default=os.getcwd(), help="project directory (default: cwd; walks up to a .claude/ or the git root)")
    ap.add_argument("--settings", default=None, help="a JSON file or string, as `claude --settings` would take")
    ap.add_argument("--key", default=None, help="only this key / subtree, itemized")
    ap.add_argument("--explain", default=None, metavar="KEY", help="describe a key from the settings index")
    ap.add_argument("--problems-only", action="store_true", help="findings only, no table")
    ap.add_argument("--full", action="store_true", help="itemize every list and do not truncate values")
    ap.add_argument("--strict", action="store_true", help="exit 1 on any error-level finding")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--claude-home", default=str(Path.home() / ".claude"), help=argparse.SUPPRESS)
    ap.add_argument("--claude-json", default=None, help=argparse.SUPPRESS)
    ap.add_argument("--managed-dir", default=None, help=argparse.SUPPRESS)
    a = ap.parse_args(argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if a.explain:
        return explain(a.explain)
    rep = build(a)
    if a.json:
        print(json.dumps(asdict(rep), indent=2, default=str))
    else:
        render(rep, a)
    if a.strict and any(f.severity == "error" for f in rep.findings):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
