"""Regenerate the SETTINGS_INDEX block in effective.py from the Claude Code docs.

Run from the repo root:  python docs/update_index.py [path/to/settings-reference.md]

With no argument it downloads https://code.claude.com/docs/en/settings-reference.md.
Stdlib only. It rewrites only the text between the two marker lines in the script
and prints how many keys changed, so a diff of effective.py shows exactly what moved.
"""
from __future__ import annotations

import datetime as dt
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "skills" / "settings-effective" / "scripts" / "effective.py"
URL = "https://code.claude.com/docs/en/settings-reference.md"
BEGIN, END = "# --- SETTINGS_INDEX begin", "# --- SETTINGS_INDEX end"
ROW = re.compile(r"^\| \[`([^`]+)`\]\([^)]*\)\s*\|(.*)$", re.M)
LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
MAX_DESC = 96


def fetch(arg: str | None) -> str:
    if arg:
        return Path(arg).read_text(encoding="utf-8")
    req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0 settings-effective/update_index"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def parse(text: str) -> dict[str, tuple[str, str, str]]:
    out: dict[str, tuple[str, str, str]] = {}
    for key, rest in ROW.findall(text):
        cells = [c.strip() for c in rest.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        desc = LINK.sub(r"\1", cells[0]).replace("`", "")
        desc = re.sub(r"\s+", " ", desc).strip()
        if len(desc) > MAX_DESC:
            desc = desc[: MAX_DESC - 1].rstrip() + "…"
        topic, scope = cells[1], cells[2]
        out[key] = (scope, topic, desc)
    return out


def render(index: dict[str, tuple[str, str, str]], when: str) -> str:
    lines = [BEGIN,
             f"# Generated by docs/update_index.py from {URL} on {when}. Do not edit by hand.",
             f"INDEX_DATE = {when!r}",
             "SETTINGS_INDEX: dict[str, tuple[str, str, str]] = {   # key: (scope, topic, description)"]
    for k in sorted(index):
        s, t, d = index[k]
        lines.append(f"    {k!r}: ({s!r}, {t!r}, {d!r}),")
    lines.append("}")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    text = fetch(sys.argv[1] if len(sys.argv) > 1 else None)
    index = parse(text)
    if len(index) < 100:
        print(f"only {len(index)} rows parsed - page layout changed?", file=sys.stderr)
        return 1
    src = SCRIPT.read_text(encoding="utf-8")
    b, e = src.index(BEGIN), src.index(END) + len(END)
    old = src[b:e]
    old_keys = set(re.findall(r"^    '([^']+)':", old, re.M))
    new = render(index, dt.date.today().isoformat())
    SCRIPT.write_text(src[:b] + new + src[e:], encoding="utf-8")
    added, removed = sorted(set(index) - old_keys), sorted(old_keys - set(index))
    print(f"{len(index)} keys; +{len(added)} -{len(removed)}")
    for k in added:
        print(f"  + {k}")
    for k in removed:
        print(f"  - {k}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
